# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "appliedgo"
license = "MIT"
licenselink = "https://github.com/christophberger/hugo-theme-appliedgo/blob/main/LICENSE.md"
description = ""
homepage = "https://github.com/christophberger/hugo-theme-appliedgo"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "Christoph Berger"
  homepage = "https://christophberger.com"

# If porting an existing theme
[original]
  name = "Icarus"
  homepage = "https://github.com/digitalcraftsman/hugo-icarus-theme"
  repo = "https://github.com/digitalcraftsman/hugo-icarus-theme"
